### ISSUE TITLE
Cannot Create items

### ISSUE THREAD

**Issue by Lockbox313** [anvil-vtt/BrokenCompass#74]
type: may not be undefined

**Comment by PatrickBauer** [comment]
A new update was pushed today, could you check if this helped? If not, I'd need a better error description of what you're trying to do 🙏

**Comment by Lockbox313** [comment]
Version 1.08 the Error is pretty obvious. click Create Item, give it name click Create New Item 
foundry.js:655 Error: Item validation errors:
  type: may not be undefined
    at DataModelValidationFailure.asError (foundry-esm.js:4710:14)
    at Item.validate (foundry-esm.js:10432:61)
    at new DataModel (foundry-esm.js:10181:12)
    at new BaseItem (foundry-esm.js:14686:7)
    at new ClientDocumentMixin (foundry.js:10594:7)
    at new Item (foundry.js:19401:1)
    at #preCreateDocumentArray (foundry-esm.js:56385:17)
    at ClientDatabaseBackend._createDocuments (foundry-esm.js:56347:58)
    at ClientDatabaseBackend.create (foundry-esm.js:12281:19)
    at async Item.createDocuments (foundry-esm.js:11423:23)
foundry.js:7207

![image](https://github.com/user-attachments/assets/11b625d1-f6bf-4e4d-b8bf-32eaa052fef4)

**Comment by PatrickBauer** [comment]
@Lockbox313 Thank you, just took a look at that and the answer is simple: There are no items in the broken compass system. And Foundry does not allow items without a type to be created 🙏
